// ─────────────────────────────────────────────────────────────────────────────
// MnemoCanvas — CLI Template
// Generates a full Node.js CLI project wired to the Mnemosyne ecosystem
// ─────────────────────────────────────────────────────────────────────────────

import type { CanvasFile } from '../../renderer.js';

export const CLI_TEMPLATE: CanvasFile[] = [

  // ── package.json ─────────────────────────────────────────────────────────
  {
    path: 'package.json',
    content: `{
  "name": "{{PROJECT_SLUG}}",
  "version": "0.1.0",
  "description": "{{PROJECT_NAME}} — Built with MnemoForge · Mnemosyne Neural OS",
  "type": "module",
  "bin": {
    "{{PROJECT_SLUG}}": "./dist/cli.js"
  },
  "main": "dist/cli.js",
  "scripts": {
    "build": "tsc",
    "dev": "tsc -w",
    "start": "node dist/cli.js",
    "prepublishOnly": "npm run build"
  },
  "keywords": ["cli", "mnemosyne", "{{PROJECT_SLUG}}"],
  "author": "{{AUTHOR}} <{{AUTHOR_EMAIL}}>",
  "license": "MIT",
  "engines": { "node": ">=18.0.0" },
  "dependencies": {
    "chalk": "^4.1.2",
    "commander": "^11.1.0",
    "inquirer": "^8.2.6"
  },
  "devDependencies": {
    "@types/inquirer": "^8.2.10",
    "@types/node": "^20.10.0",
    "typescript": "^5.3.3"
  }
}
`,
  },

  // ── tsconfig.json ─────────────────────────────────────────────────────────
  {
    path: 'tsconfig.json',
    content: `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "Node16",
    "moduleResolution": "Node16",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
`,
  },

  // ── .gitignore ────────────────────────────────────────────────────────────
  {
    path: '.gitignore',
    content: `node_modules/
dist/
*.log
.DS_Store
Thumbs.db
`,
  },

  // ── .cursorrules ──────────────────────────────────────────────────────────
  {
    path: '.cursorrules',
    content: `# {{PROJECT_NAME}} — AI Governance Rules
# Generated by MnemoForge v{{MNEMOFORGE_VERSION}} on {{DATE}}
# Workspace: {{WORKSPACE}}

## Identity
You are working on **{{PROJECT_NAME}}**, a CLI tool built within the Mnemosyne Neural OS ecosystem.

## Language & Stack
- TypeScript 5 (strict mode) — zero \`any\` tolerance
- Node.js 18+ (ESM modules)
- Commander.js for command structure
- Chalk for terminal colors
- Inquirer.js for interactive prompts

## Code Standards
- All functions must have explicit return types
- Use \`chalk.hex()\` for colors — never plain chalk colors
- Error handling: always use \`process.exit(1)\` on fatal errors
- Console output: always prefix with 2 spaces for alignment

## Chronicle & Memory
- Before starting a session, run: \`mnemoforge workspace show\`
- After key decisions, write a chronicle in \`handbook/chronicles/\`
- Archive chronicles with: \`mnemoforge chronicle archive --file <path>\`

## Mnemosyne Neural OS
This project is part of the Mnemosyne ecosystem.
Repository: https://github.com/yaka0007/Mnemosyne-Neural-OS
`,
  },

  // ── AGENT_INSTRUCTIONS.md ─────────────────────────────────────────────────
  {
    path: 'AGENT_INSTRUCTIONS.md',
    content: `# {{PROJECT_NAME}} — Agent Mission Directive
*Generated by MnemoForge v{{MNEMOFORGE_VERSION}} · {{DATE}}*

## Context
You are an AI agent (Cursor, Claude, Copilot, or similar) working on **{{PROJECT_NAME}}**.
This is a CLI tool built within the **{{WORKSPACE}}** workspace of the Mnemosyne Neural OS ecosystem.

## Before You Start
1. Run \`mnemoforge workspace show\` to read the project safety rules
2. Read the latest chronicle: \`mnemoforge chronicle open\`
3. Check the vault: \`mnemoforge chronicle list\`

## Your Mission
Build and maintain {{PROJECT_NAME}} according to Mnemosyne standards:
- TypeScript strict, no \`any\`
- Clean terminal UX with chalk color palette
- Write a chronicle after each significant session

## After You Finish
Archive your session chronicle:
\`\`\`bash
mnemoforge chronicle archive --file handbook/chronicles/CHRONICLE-YYYY-MM-DD-session.md
\`\`\`

*"The model may not know who it is. The soul does."*
`,
  },

  // ── WORKSPACE.json ────────────────────────────────────────────────────────
  {
    path: 'WORKSPACE.json',
    content: `{
  "workspace": "{{WORKSPACE}}",
  "project": "{{PROJECT_NAME}}",
  "version": "0.1.0",
  "created": "{{DATE}}",
  "last_updated": "{{DATE}}",
  "updated_by": "MnemoForge canvas",
  "npm": {
    "rules": [
      "Always bump version before npm publish",
      "Run pnpm run build before publish",
      "Never publish with node_modules in package"
    ]
  },
  "architecture": {
    "rules": [
      "TypeScript strict — zero any",
      "Commander.js for all command structure",
      "Chalk hex colors only — no plain chalk colors",
      "All errors use process.exit(1)"
    ]
  },
  "neural_coding": {
    "principles": [
      "Read workspace rules before starting any session",
      "Write a chronicle after each significant decision",
      "The agent understands context — no mechanical re-explanations"
    ]
  }
}
`,
  },

  // ── src/cli.ts ────────────────────────────────────────────────────────────
  {
    path: 'src/cli.ts',
    content: `#!/usr/bin/env node
// {{PROJECT_NAME}} CLI
// Generated by MnemoForge v{{MNEMOFORGE_VERSION}} · {{DATE}}

import { Command } from 'commander';
import chalk from 'chalk';

// ── Color palette ─────────────────────────────────────────────────────────
const V  = chalk.hex('#8B5CF6');
const V2 = chalk.hex('#A78BFA');
const DIM = chalk.gray;

// ── Program ───────────────────────────────────────────────────────────────
const program = new Command()
  .name('{{PROJECT_SLUG}}')
  .description('{{PROJECT_NAME}} — Built with MnemoForge · Mnemosyne Neural OS')
  .version('0.1.0', '-v, --version')
  .action(() => {
    console.log(V.bold('\\n  ⬡  {{PROJECT_NAME}}\\n'));
    console.log(DIM('  A Mnemosyne-grade CLI.'));
    console.log(DIM('  Run ') + chalk.white('{{PROJECT_SLUG}} --help') + DIM(' to see commands.\\n'));
  });

// ── Example command ───────────────────────────────────────────────────────
program
  .command('hello')
  .description('Say hello')
  .action(() => {
    console.log(V2.bold('\\n  ⬡  {{PROJECT_NAME}}\\n'));
    console.log(chalk.white('  Hello from {{PROJECT_NAME}}! 👋\\n'));
  });

program.parse(process.argv);
`,
  },

  // ── handbook/chronicles/.gitkeep ─────────────────────────────────────────
  {
    path: 'handbook/chronicles/.gitkeep',
    content: '',
  },

  // ── ROADMAP.md ────────────────────────────────────────────────────────────
  {
    path: 'ROADMAP.md',
    content: `# {{PROJECT_NAME}} — Roadmap
*Generated by MnemoForge v{{MNEMOFORGE_VERSION}} · {{DATE}}*
*Workspace: {{WORKSPACE}}*

---

## Context

**{{PROJECT_NAME}}** is a CLI tool built within the {{WORKSPACE}} ecosystem.
This file is the **source of truth for any agent** working on this project.
Read it before starting any session.

## Current State

- Version: 0.1.0
- Stack: Node.js · TypeScript · Commander.js · Chalk · Inquirer
- Chronicles vault: \`handbook/chronicles/\`

## Before You Start (Agent Checklist)

1. Read this file
2. Run \`mnemoforge workspace show\` for safety rules
3. Run \`mnemoforge chronicle list\` to see recent decisions

---

## Phase 0 — Foundation *(current)*

- [x] Project scaffolded with MnemoForge canvas
- [ ] Core command structure in \`src/cli.ts\`
- [ ] First release published

## Phase 1 — Core Features

> Define your features here

- [ ] Feature A
- [ ] Feature B

## Phase 2 — Polish

> Testing, documentation, UX

- [ ] Unit tests
- [ ] README documentation
- [ ] First public release

---

## Key Decisions

> Log important architectural decisions here as you go.
> Example: "2026-04-05 — Chose Commander.js over yargs for simpler API"

| Date | Decision | Rationale |
|------|----------|-----------|
| {{DATE}} | Project created with MnemoForge canvas | Standard Mnemosyne CLI template |

---

## Agent Notes

*Add notes for your AI agent here — context, constraints, things to remember.*

- This project follows Mnemosyne Neural OS coding standards
- Write a chronicle after significant work sessions
`,
  },
];
